### ISSUE TITLE
Resolve import/export incompatibility between Node/CommonJS and ESM

### ISSUE THREAD

**Issue by timbl** [solid/mashlib#44]
We have been attempting to incrementally start using ES import and export in certain modules but not others, at the same time as we move from JS to TS.   In fact the module systems are as implemented in node at least, not compatible as we have used them.    The result is currently a mess.   The pane module API is varies depending on which language you have written the pane module in, which is no way to run a restaurant.

For example in  https://github.com/solid/solid-panes/blob/dev/index.js half the modules are called with a new `.default` and half are not.

See recent notes about this 

https://2ality.com/2019/04/nodejs-esm-impl.html 

https://github.com/nodejs/modules/blob/master/doc/announcement.md#es-module-code-in-packages  Which says among other things, 

> "Please do not publish any ES module packages intended for use by Node.js until this is resolved."

An extra complication is that our pipeline generates js files from ts files using tsc .. so it is tsc which defines the mapping from import to require, not the native es implementation in node or

**Comment by Vinnl** [comment]
> An extra complication is that our pipeline generates js files from ts files using tsc .. so it is tsc which defines the mapping from import to require, not the native es implementation in node or

Something appears to be missing at the end of that sentence...

Anyway, I'm not quite sure what branch of mashlib I'm supposed to be looking at, but `master` and `dev` do not to TypeScript at all, as far as I can see. In solid-panes, JS files are _not_ generated by `tsc`, but using Babel, just like mashlib does, as far as I can see.

I personally prefer the explicitness of named exports over the use of default exports; I merely went with using default exports to remain as consistent with existing code as possible. Moving to named exports should be far easier once everything is in TypeScript anyway.

I started on the TypeScript conversion because that was an action item in the revamp document, going for incremental conversion rather than big-bang - which is why there are two different modules systems in use now. To reach consistency there more quickly, we could e.g. also opt to move all Panes to regular Javascript modules rather than CommonJS _before_ moving them to TypeScript?

**Comment by megoth** [comment]
(Thanks to @melvincarvalho for reminding me of this issue.)

I think we've solved this issue by:

1. Keeping the public APIs from mashlib (and related projects maintained by the Solid Data Browser team at inrupt, such as solid-panes and solid-ui) as is (meaning CJS modules), but to add slowly migrate to ESM by:
  * Leaving an alias for all parts that are removed to ESM, that will show a deprecation warning (using something like `console.warn`)
  * Keep the alias for at least a year or so, and then remove it in a major version
2. [Support both CJS modules and ESM for views](https://github.com/solid/solid-panes/pull/202)

Please reopen this issue if I've missed something.
